### ISSUE TITLE
Not all pages are published to gh-pages

### ISSUE THREAD

**Issue by joymon** [chabad360/hugo-gh-pages#11]
Below is my repo. When I run locally it shows all the 7 menus and pages. But when published to gh-pages in same repo, its showing only 2 pages Home & Links.

Repo - https://github.com/joymon/site-hugo
Site - https://joymon.github.io/site-hugo/

Any help is really appreciated.

**Comment by chabad360** [comment]
I see all the pages (on your site), so I'm not quite sure whats wrong...

**Comment by joymon** [comment]
Thanks @chabad360, It was my mistake. Missed the basics. Those pages were draft:true. Closing the issue
