### ISSUE TITLE
Allow to use other account instead of GITHUB_ACTOR commit

### ISSUE THREAD

**Issue by CoelacanthusHex** [chabad360/hugo-gh-pages#18]

**Comment by chabad360** [comment]
Can you please elaborate?

**Comment by CoelacanthusHex** [comment]
I want to use a configurable account to commit instead of a fixed GITHUB_ACTOR
The current setting will always use GITHUB_ACTOR (that is, the committee of the source repository), but I want the committee pushed to the deployment repository to be the account I specify

My English is poor, please forgive me

**Comment by chabad360** [comment]
All you need is a GitHub Personal Access Token (PAT), if you don't want to push from your account, you can use a PAT from another account that has write access to your repository.

**Comment by CoelacanthusHex** [comment]
You fixed committee/author (not pusher) in the code

https://github.com/chabad360/hugo-gh-pages/blob/master/docker-entrypoint.sh#L52-L53

**Comment by CoelacanthusHex** [comment]
And this will not change with Personal Token

**Comment by chabad360** [comment]
Oh, that's what you meant. That's just the name that's used for the commit information, if you want to change that you should transfer the repo to user you want it to push from, and then give yourself write permission to that repo. It doesn't really make sense to make this value customizable.
