### ISSUE TITLE
Getting Hugo binary fails on un-tarring

### ISSUE THREAD

**Issue by bashopman** [chabad360/hugo-gh-pages#4]
Using version chabad360/hugo-gh-pages@master

First of all, your action has worked like a charm for me. Thanks for creating it!

But... as of February 13th, 2020 your action has started to fail showing message:
```
tar: invalid magic
tar: short read
tar: hugo_extended_0.64.1_Linux-64bit.tar.gz: not found in archive
```
see also: https://github.com/coderdojonijmegen/hugo-coderdojo-nijmegen/runs/444040083?check_suite_focus=true

Initially I ran it using Hugo extended 0.64.0, so after it started failing, I changed to 0.64.1 to verify if that worked. Sadly, that didn't solve the problem.

I cannot validate if the downloaded tar was corrupt or not, so maybe you can check what's going on?

Thanks!

Bas

**Comment by chabad360** [comment]
I can't seem to reproduce the error (just by downloading and untaring manually), so maybe just try it again (perhaps you got lucky in some way). If the issue persists I will persue it further.

**Comment by bashopman** [comment]
Hi @chabad360 ,

Thanks for checking!
I just ran my action again, but it still fails.
As it ran successfully previously and started failing without change from my side, I have no means to debug. The logging I linked to in my previous message, does not show where the Hugo tar is downloaded from. So, I cannot check the tar by downloading and untarring myself.
I did find information on the internet that Alpines BusyBox version does not support all tar functionality, which may cause the problem...
Hope you can help.

Bas

**Comment by chabad360** [comment]
Should be fixed by [`1f74cfa`](https://github.com/chabad360/hugo-gh-pages/commit/1f74cfa18e297144446a1ff36ab19128899a6be1).

**Comment by bashopman** [comment]
@chabad360 Your fix hadn't worked for me and I finally found why....
I had an IntellJ project file starting with `hugo` in my workspace. This resulted in that file being un-tarred, which obviously isn't working.
You might want to consider using `tar -xzvf hugo*.tar.gz` to make sure a .tar.gz file is being extracted?

Bas

**Comment by chabad360** [comment]
Ok. Thanks for the suggestion 👍.
