### ISSUE TITLE
Build from non-root

### ISSUE THREAD

**Issue by EricStG** [chabad360/hugo-gh-pages#6]
Is it possible to trigger the build from a directory other than the root of the repo?
etc: `/src` or something

**Comment by chabad360** [comment]
Try using it now with the `siteDir` argument set to whatever your directory is. Close if it works.

**Comment by EricStG** [comment]
There's an error in `action.yml`
https://github.com/chabad360/hugo-gh-pages/blob/master/action.yml#L33
The quote in `it's` is messing up the string

**Comment by EricStG** [comment]
Still having issues after fixing that. 
`/entrypoint.sh: cd: line 63: can't cd to src/hugo: No such file or directory`

**Comment by chabad360** [comment]
> The quote in `it's` is messing up the string

Whoops, fixed that.

> Still having issues after fixing that.
> `/entrypoint.sh: cd: line 63: can't cd to src/hugo: No such file or directory`

Did you write `/src/hugo` (make sure to include the first slash)?

**Comment by EricStG** [comment]
I tried both with and without a starting `/` with no luck

**Comment by chabad360** [comment]
Ah, the correct repo root is at `/github/workspace`, so try `/github/workspace/hugo` (see [here](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem)).

**Comment by chabad360** [comment]
lmk if that works.

**Comment by chabad360** [comment]
It would appear that you forgot to add the checkout repo action:

```yml
steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
```

Add that before the `hugo-gh-pages` action and you should be good.

**Comment by EricStG** [comment]
urg yeah that was it. Got it working now, thanks for the extra feature and the help!

**Comment by chabad360** [comment]
You're welcome!
