### ISSUE TITLE
error during publish:  /entrypoint.sh: cd: line 61: can't cd to (pwd): No such file or directory

### ISSUE THREAD

**Issue by larryclaman** [chabad360/hugo-gh-pages#8]
Action was working for me for a while, but I think a regression crept in.  I'm currently getting the following error during the publish process:

```
Cloning into '/tmp/gh-pages'...
/entrypoint.sh: cd: line 61: can't cd to (pwd): No such file or directory
```

**Comment by larryclaman** [comment]
sorry!  my bad; I'll open it in the other repo!

**Comment by chabad360** [comment]
to late, been there done that

**Comment by larryclaman** [comment]
confirmed working now; thanks for the quick fix!

**Comment by chabad360** [comment]
You're welcome.
